"""Training ecosystem models for AI-enhanced training capabilities.

This module defines the database models for the AI-Enhanced Training Ecosystem
(Phase 5.3), including:
- TrainingSchedule: Personalized AI-generated training schedules
- SkillGap: Identified gaps between required and completed training
- TrainingMaterial: AI-generated educational content from SOPs
- GeneratedQuestion: AI-generated comprehension assessment questions
- VirtualAuditSession: Interactive role-play virtual audit sessions
- DynamicFeedbackCache: Cached paragraph-level feedback for incorrect answers

All models with AuditMixin are versioned via SQLAlchemy-Continuum for
full GxP audit trail compliance.

References:
    - ALCOA+ data integrity: attributable, legible, contemporaneous, original, accurate
    - Educational Specialist archetype (5.1) provides generation prompts
    - InferenceClient (4.3) handles all LLM inference calls
"""

from datetime import datetime
from enum import Enum
from typing import Any

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSON, JSONB
from sqlalchemy.orm import Mapped, mapped_column

from alcoabase.database import Base
from alcoabase.models.audit import AuditMixin


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class GapType(str, Enum):
    """Types of skill gaps identified during analysis."""

    MISSING_TRAINING = "missing_training"
    EXPIRED_TRAINING = "expired_training"
    NEW_VERSION_AVAILABLE = "new_version_available"


class PriorityLevel(str, Enum):
    """Priority levels for training items and skill gaps."""

    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


class MaterialType(str, Enum):
    """Types of AI-generated training materials."""

    EXECUTIVE_SUMMARY = "executive_summary"
    DETAILED_WALKTHROUGH = "detailed_walkthrough"
    KEY_TAKEAWAYS = "key_takeaways"
    PRESENTATION_OUTLINE = "presentation_outline"
    SAFETY_HIGHLIGHTS = "safety_highlights"


class QuestionType(str, Enum):
    """Types of AI-generated comprehension questions."""

    MULTIPLE_CHOICE = "multiple_choice"
    TRUE_FALSE = "true_false"
    SCENARIO_BASED = "scenario_based"
    FILL_IN_BLANK = "fill_in_blank"


class DifficultyLevel(str, Enum):
    """Difficulty levels for generated questions."""

    BASIC = "basic"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


class SessionStatus(str, Enum):
    """Status of a virtual audit session."""

    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    ABANDONED = "abandoned"


class ContentStatus(str, Enum):
    """Status of AI-generated content (materials, questions)."""

    PENDING_REVIEW = "pending_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    DRAFT = "draft"


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class TrainingSchedule(Base, AuditMixin):
    """Personalized AI-generated training schedule for a user.

    Each user has at most one active schedule per company. The schedule
    contains ordered training items with priorities, deadlines, and
    completion tracking. Schedules are regenerated on demand via the
    Educational Specialist agent archetype.

    Attributes:
        id: Primary key.
        user_id: Foreign key to the user this schedule belongs to.
        company_id: Foreign key to the owning company (tenant isolation).
        schedule_data: JSONB containing ordered training items with metadata.
        compliance_percentage: Computed percentage of completed training.
        total_items: Total number of training items in the schedule.
        completed_items: Number of completed training items.
        generated_at: Timestamp when the schedule was generated by AI.
        last_recalculated_at: Timestamp of last gap recalculation.
        created_at: Server-side UTC timestamp of creation.
        updated_at: Timestamp of last update.
    """

    __tablename__ = "training_schedules"
    __table_args__ = (
        UniqueConstraint(
            "user_id", "company_id", name="uq_training_schedule_user_company"
        ),
        CheckConstraint(
            "completed_items <= total_items",
            name="ck_schedule_completed_lte_total",
        ),
        Index("ix_training_schedule_user_company", "user_id", "company_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
    company_id: Mapped[int] = mapped_column(ForeignKey("companies.id"))
    schedule_data: Mapped[dict] = mapped_column(JSONB)
    compliance_percentage: Mapped[float] = mapped_column(default=0.0)
    total_items: Mapped[int] = mapped_column(default=0)
    completed_items: Mapped[int] = mapped_column(default=0)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    last_recalculated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True)
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), onupdate=func.now(), nullable=True
    )


class SkillGap(Base):
    """Identified skill gap between required and completed training.

    Skill gaps are computed as the set difference of required documents
    (based on role assignments) minus completed training records. Gaps
    are created and resolved during periodic recalculation.

    Attributes:
        id: Primary key.
        user_id: Foreign key to the user with the gap.
        company_id: Foreign key to the owning company (tenant isolation).
        document_id: Foreign key to the document requiring training.
        document_version_id: Foreign key to the specific version required.
        gap_type: Classification of the gap (missing, expired, new version).
        priority: Computed priority level based on deadline and access gating.
        days_overdue: Number of days past the training deadline (nullable).
        blocks_access: Whether this gap blocks document access.
        identified_at: Timestamp when the gap was first identified.
        resolved_at: Timestamp when the gap was resolved (nullable).
        created_at: Server-side UTC timestamp of creation.
    """

    __tablename__ = "skill_gaps"
    __table_args__ = (
        UniqueConstraint(
            "user_id",
            "document_id",
            "document_version_id",
            "gap_type",
            name="uq_skill_gap_user_doc_version_type",
        ),
        Index("ix_skill_gap_user_company", "user_id", "company_id"),
        Index(
            "ix_skill_gap_document", "document_id", "document_version_id"
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
    company_id: Mapped[int] = mapped_column(ForeignKey("companies.id"))
    document_id: Mapped[int] = mapped_column(ForeignKey("documents.id"))
    document_version_id: Mapped[int] = mapped_column(
        ForeignKey("document_versions.id")
    )
    gap_type: Mapped[GapType] = mapped_column()
    priority: Mapped[PriorityLevel] = mapped_column()
    days_overdue: Mapped[int | None] = mapped_column(nullable=True, default=0)
    blocks_access: Mapped[bool] = mapped_column(default=False)
    identified_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class TrainingMaterial(Base, AuditMixin):
    """AI-generated training material from a source document.

    Materials are generated by the Educational Specialist agent archetype
    and must pass coordinator review before being presented to trainees.
    Each document version can have one material per type.

    Attributes:
        id: Primary key.
        document_id: Foreign key to the source document.
        document_version_id: Foreign key to the specific version used.
        company_id: Foreign key to the owning company (tenant isolation).
        material_type: Type of material (summary, walkthrough, etc.).
        content_data: JSONB containing the structured material content.
        learning_objectives: JSON list of learning objectives.
        estimated_duration_minutes: Estimated time to complete the material.
        status: Review status (pending_review, approved, rejected, draft).
        generated_by_agent_id: ID of the agent archetype that generated this.
        inference_duration_ms: Time taken for LLM inference in milliseconds.
        reviewed_by: Foreign key to the reviewer user (nullable).
        reviewed_at: Timestamp of review (nullable).
        created_at: Server-side UTC timestamp of creation.
        updated_at: Timestamp of last update.
    """

    __tablename__ = "training_materials"
    __table_args__ = (
        UniqueConstraint(
            "document_id",
            "document_version_id",
            "material_type",
            name="uq_training_material_doc_version_type",
        ),
        Index(
            "ix_training_material_doc_version",
            "document_id",
            "document_version_id",
        ),
        Index("ix_training_material_status", "status"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    document_id: Mapped[int] = mapped_column(ForeignKey("documents.id"))
    document_version_id: Mapped[int] = mapped_column(
        ForeignKey("document_versions.id")
    )
    company_id: Mapped[int] = mapped_column(ForeignKey("companies.id"))
    material_type: Mapped[MaterialType] = mapped_column()
    content_data: Mapped[dict] = mapped_column(JSONB)
    learning_objectives: Mapped[list] = mapped_column(JSON)
    estimated_duration_minutes: Mapped[int] = mapped_column()
    status: Mapped[str] = mapped_column(
        String(20), default=ContentStatus.PENDING_REVIEW.value
    )
    generated_by_agent_id: Mapped[str | None] = mapped_column(
        String(255), nullable=True
    )
    inference_duration_ms: Mapped[int | None] = mapped_column(nullable=True)
    reviewed_by: Mapped[int | None] = mapped_column(
        ForeignKey("users.id"), nullable=True
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), onupdate=func.now(), nullable=True
    )

    def __init__(self, **kwargs: Any) -> None:
        """Initialize TrainingMaterial with pending_review status default."""
        if "status" not in kwargs:
            kwargs["status"] = ContentStatus.PENDING_REVIEW.value
        super().__init__(**kwargs)


class GeneratedQuestion(Base, AuditMixin):
    """AI-generated comprehension question for training assessments.

    Questions are generated from source documents with validated answers,
    section references, and difficulty levels. They must pass coordinator
    review before being served in active assessments.

    Attributes:
        id: Primary key.
        document_id: Foreign key to the source document.
        document_version_id: Foreign key to the specific version used.
        company_id: Foreign key to the owning company (tenant isolation).
        question_text: The full question text.
        question_type: Type of question (MC, T/F, scenario, fill-in-blank).
        correct_answer: The correct answer text.
        distractors: JSON list of incorrect answer options (for MC).
        explanation: Explanation of why the answer is correct.
        difficulty_level: Question difficulty (basic, intermediate, advanced).
        bloom_taxonomy_level: Bloom's taxonomy classification.
        sop_section_ref: Reference to the source SOP section.
        status: Review status (pending_review, approved, rejected, draft).
        reviewed_by: Foreign key to the reviewer user (nullable).
        reviewed_at: Timestamp of review (nullable).
        created_at: Server-side UTC timestamp of creation.
        updated_at: Timestamp of last update.
    """

    __tablename__ = "generated_questions"
    __table_args__ = (
        Index(
            "ix_generated_question_doc_version",
            "document_id",
            "document_version_id",
        ),
        Index("ix_generated_question_status", "status"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    document_id: Mapped[int] = mapped_column(ForeignKey("documents.id"))
    document_version_id: Mapped[int] = mapped_column(
        ForeignKey("document_versions.id")
    )
    company_id: Mapped[int] = mapped_column(ForeignKey("companies.id"))
    question_text: Mapped[str] = mapped_column(Text)
    question_type: Mapped[QuestionType] = mapped_column()
    correct_answer: Mapped[str] = mapped_column(Text)
    distractors: Mapped[list | None] = mapped_column(JSON, nullable=True)
    explanation: Mapped[str] = mapped_column(Text)
    difficulty_level: Mapped[DifficultyLevel] = mapped_column()
    bloom_taxonomy_level: Mapped[str] = mapped_column(String(50))
    sop_section_ref: Mapped[str] = mapped_column(String(500))
    status: Mapped[str] = mapped_column(
        String(20), default=ContentStatus.PENDING_REVIEW.value
    )
    reviewed_by: Mapped[int | None] = mapped_column(
        ForeignKey("users.id"), nullable=True
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), onupdate=func.now(), nullable=True
    )

    def __init__(self, **kwargs: Any) -> None:
        """Initialize GeneratedQuestion with pending_review status default."""
        if "status" not in kwargs:
            kwargs["status"] = ContentStatus.PENDING_REVIEW.value
        super().__init__(**kwargs)


class VirtualAuditSession(Base, AuditMixin):
    """Interactive virtual audit role-play session.

    Sessions track progressive-difficulty conversational assessments where
    users demonstrate document comprehension. Passed sessions create
    synthetic QuizAttempt records for backward compatibility with the
    training gate.

    Attributes:
        id: Primary key.
        user_id: Foreign key to the user being assessed.
        document_id: Foreign key to the document being assessed on.
        document_version_id: Foreign key to the specific version.
        company_id: Foreign key to the owning company (tenant isolation).
        status: Session status (in_progress, completed, abandoned).
        overall_score: Weighted average score across all turns (nullable).
        passed: Whether the session meets passing criteria (nullable).
        turns_completed: Number of turns completed so far.
        total_turns: Total turns determined by document section count.
        session_data: JSONB containing turn-by-turn interaction data.
        summary_data: JSONB containing session summary (nullable).
        started_at: Timestamp when the session started.
        completed_at: Timestamp when the session ended (nullable).
        created_at: Server-side UTC timestamp of creation.
    """

    __tablename__ = "virtual_audit_sessions"
    __table_args__ = (
        CheckConstraint(
            "turns_completed <= total_turns",
            name="ck_session_turns_lte_total",
        ),
        Index(
            "ix_virtual_audit_user_company", "user_id", "company_id"
        ),
        Index("ix_virtual_audit_user_doc", "user_id", "document_id"),
        Index("ix_virtual_audit_status", "status"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
    document_id: Mapped[int] = mapped_column(ForeignKey("documents.id"))
    document_version_id: Mapped[int] = mapped_column(
        ForeignKey("document_versions.id")
    )
    company_id: Mapped[int] = mapped_column(ForeignKey("companies.id"))
    status: Mapped[SessionStatus] = mapped_column(
        default=SessionStatus.IN_PROGRESS
    )
    overall_score: Mapped[float | None] = mapped_column(nullable=True)
    passed: Mapped[bool | None] = mapped_column(nullable=True)
    turns_completed: Mapped[int] = mapped_column(default=0)
    total_turns: Mapped[int] = mapped_column()
    session_data: Mapped[dict] = mapped_column(JSONB, default=dict)
    summary_data: Mapped[dict | None] = mapped_column(
        JSONB, nullable=True
    )
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class ActiveQuestionSet(Base):
    """Tracks which AI-generated question sets are active for quiz submission.

    When approved questions are registered via QuizService.register_approved_questions,
    an ActiveQuestionSet record is created linking the content_id to the document
    and version. Previous sets for the same content_id are marked inactive.

    Attributes:
        id: Primary key.
        content_id: Training content identifier ({document_uuid}_v{sop_version}).
        document_id: Foreign key to the source document.
        document_version_id: Foreign key to the specific version.
        company_id: Foreign key to the owning company (tenant isolation).
        is_active: Whether this question set is currently active.
        registered_at: Timestamp when the set was registered.
        created_at: Server-side UTC timestamp of creation.
    """

    __tablename__ = "active_question_sets"
    __table_args__ = (
        Index("ix_active_question_set_content", "content_id"),
        Index(
            "ix_active_question_set_doc_version",
            "document_id",
            "document_version_id",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    content_id: Mapped[str] = mapped_column(String(255))
    document_id: Mapped[int] = mapped_column(ForeignKey("documents.id"))
    document_version_id: Mapped[int] = mapped_column(
        ForeignKey("document_versions.id")
    )
    company_id: Mapped[int] = mapped_column(ForeignKey("companies.id"))
    is_active: Mapped[bool] = mapped_column(default=True)
    registered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class DynamicFeedbackCache(Base):
    """Cached paragraph-level feedback for incorrect quiz answers.

    Caches RAG-retrieved paragraphs and LLM-generated explanations to
    avoid repeated inference calls. Cache is invalidated when a new
    document version is published.

    Attributes:
        id: Primary key.
        question_id: Foreign key to the generated question.
        document_version_id: Foreign key to the document version.
        paragraph_text: Retrieved source paragraph text.
        section_reference: SOP section reference string.
        page_number: Page number in the source document (nullable).
        similarity_score: Cosine similarity score from RAG retrieval.
        explanation: LLM-generated explanation text.
        created_at: Server-side UTC timestamp of creation.
    """

    __tablename__ = "dynamic_feedback_cache"
    __table_args__ = (
        UniqueConstraint(
            "question_id",
            "document_version_id",
            name="uq_feedback_cache_question_version",
        ),
        Index("ix_feedback_cache_question", "question_id"),
        Index("ix_feedback_cache_doc_version", "document_version_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    question_id: Mapped[int] = mapped_column(
        ForeignKey("generated_questions.id")
    )
    document_version_id: Mapped[int] = mapped_column(
        ForeignKey("document_versions.id")
    )
    paragraph_text: Mapped[str] = mapped_column(Text)
    section_reference: Mapped[str] = mapped_column(String(500))
    page_number: Mapped[int | None] = mapped_column(nullable=True)
    similarity_score: Mapped[float] = mapped_column()
    explanation: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

