"""Pydantic request/response schemas for training ecosystem endpoints.

Provides validated schemas for AI-enhanced training operations including
schedule generation, material generation, question generation, role-play
virtual audits, and dynamic feedback.

References:
    - Design doc Section 9: Pydantic Schemas
    - Requirements 9.1–9.15: Training Ecosystem API Endpoints
"""

from datetime import datetime

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Request Schemas
# ---------------------------------------------------------------------------


class ScheduleGenerateRequest(BaseModel):
    """Request schema for generating a personalized training schedule.

    Attributes:
        user_id: ID of the user to generate a schedule for.
    """

    user_id: int


class MaterialGenerateRequest(BaseModel):
    """Request schema for generating training materials from a document.

    Attributes:
        document_id: Source document ID.
        document_version_id: Specific version to generate materials from.
        material_types: Optional list of material types to generate.
            Defaults to all 5 types if not specified.
    """

    document_id: int
    document_version_id: int
    material_types: list[str] | None = None


class QuestionGenerateRequest(BaseModel):
    """Request schema for generating comprehension questions.

    Attributes:
        document_id: Source document ID.
        document_version_id: Specific version to generate questions from.
        question_count: Number of questions to generate (5–20).
        difficulty_distribution: Optional distribution across difficulty levels.
    """

    document_id: int
    document_version_id: int
    question_count: int = Field(default=10, ge=5, le=20)
    difficulty_distribution: dict[str, float] | None = None


class RolePlayStartRequest(BaseModel):
    """Request schema for starting a virtual audit role-play session.

    Attributes:
        document_id: Document to be assessed on.
        document_version_id: Specific version for the assessment.
        user_id: ID of the user being assessed.
    """

    document_id: int
    document_version_id: int
    user_id: int


class RolePlayRespondRequest(BaseModel):
    """Request schema for submitting a response in a role-play session.

    Attributes:
        response_text: The user's response to the auditor question (max 2000 chars).
    """

    response_text: str = Field(max_length=2000)


# ---------------------------------------------------------------------------
# Response Schemas
# ---------------------------------------------------------------------------


class JobAcceptedResponse(BaseModel):
    """Response schema for async job acceptance (HTTP 202).

    Attributes:
        job_id: Unique identifier for the dispatched job.
        status: Initial job status, always "pending".
    """

    job_id: str
    status: str = "pending"


class TrainingScheduleResponse(BaseModel):
    """Response schema for a user's training schedule.

    Attributes:
        id: Schedule primary key.
        user_id: Owner user ID.
        schedule_data: Ordered training items with priorities and deadlines.
        compliance_percentage: Percentage of completed training (0.0–100.0).
        total_items: Total training items in the schedule.
        completed_items: Number of completed items.
        generated_at: When the schedule was generated by AI.
        last_recalculated_at: When gaps were last recalculated.
    """

    id: int
    user_id: int
    schedule_data: dict
    compliance_percentage: float = Field(ge=0.0, le=100.0)
    total_items: int = Field(ge=0)
    completed_items: int = Field(ge=0)
    generated_at: datetime
    last_recalculated_at: datetime

    model_config = {"from_attributes": True}


class SkillGapResponse(BaseModel):
    """Response schema for an individual skill gap.

    Attributes:
        id: Gap primary key.
        document_id: Document requiring training.
        document_title: Human-readable document title.
        gap_type: Classification (missing_training, expired_training, new_version_available).
        priority: Priority level (Critical, High, Medium, Low).
        days_overdue: Days past the training deadline (nullable).
        blocks_access: Whether this gap blocks document access.
        identified_at: When the gap was first identified.
    """

    id: int
    document_id: int
    document_title: str
    gap_type: str
    priority: str
    days_overdue: int | None = None
    blocks_access: bool
    identified_at: datetime

    model_config = {"from_attributes": True}


class CompanyGapReportResponse(BaseModel):
    """Response schema for company-wide skill gap report.

    Attributes:
        total_users_with_gaps: Number of users with at least one gap.
        company_compliance_percentage: Overall company compliance (0.0–100.0).
        top_documents: Top documents with the most untrained users.
        top_users: Top users with the most outstanding training items.
        by_framework: Per-regulatory-framework compliance percentages.
        total: Total number of gap records for pagination.
    """

    total_users_with_gaps: int = Field(ge=0)
    company_compliance_percentage: float = Field(ge=0.0, le=100.0)
    top_documents: list[dict]
    top_users: list[dict]
    by_framework: dict[str, float] | None = None
    total: int = Field(ge=0)


class TrainingMaterialResponse(BaseModel):
    """Response schema for a generated training material.

    Attributes:
        id: Material primary key.
        document_id: Source document ID.
        document_version_id: Source document version ID.
        material_type: Type of material generated.
        content_data: Structured material content.
        learning_objectives: List of learning objectives.
        estimated_duration_minutes: Estimated consumption time (1–480).
        status: Review status (pending_review, approved, rejected, draft).
        generated_by_agent_id: Agent archetype that generated this.
        inference_duration_ms: LLM inference time in milliseconds.
        reviewed_by: Reviewer user ID (nullable).
        reviewed_at: Review timestamp (nullable).
        created_at: Creation timestamp.
    """

    id: int
    document_id: int
    document_version_id: int
    material_type: str
    content_data: dict
    learning_objectives: list[str]
    estimated_duration_minutes: int = Field(ge=1, le=480)
    status: str
    generated_by_agent_id: str | None = None
    inference_duration_ms: int | None = None
    reviewed_by: int | None = None
    reviewed_at: datetime | None = None
    created_at: datetime

    model_config = {"from_attributes": True}


class GeneratedQuestionResponse(BaseModel):
    """Response schema for a generated comprehension question.

    Attributes:
        id: Question primary key.
        question_text: The full question text.
        question_type: Type (multiple_choice, true_false, scenario_based, fill_in_blank).
        correct_answer: Correct answer (hidden from trainees in some contexts).
        distractors: Incorrect options for multiple choice (nullable).
        explanation: Why the answer is correct (hidden until answered).
        difficulty_level: Question difficulty (basic, intermediate, advanced).
        bloom_taxonomy_level: Bloom's taxonomy classification.
        sop_section_ref: Reference to source SOP section.
        status: Review status.
        created_at: Creation timestamp.
    """

    id: int
    question_text: str
    question_type: str
    correct_answer: str | None = None
    distractors: list[str] | None = None
    explanation: str | None = None
    difficulty_level: str
    bloom_taxonomy_level: str
    sop_section_ref: str
    status: str
    created_at: datetime

    model_config = {"from_attributes": True}


class VirtualAuditSessionResponse(BaseModel):
    """Response schema for a virtual audit role-play session.

    Attributes:
        id: Session primary key.
        user_id: User being assessed.
        document_id: Document being assessed on.
        status: Session status (in_progress, completed, abandoned).
        overall_score: Weighted average score (0.0–1.0, nullable).
        passed: Whether the session meets passing criteria (nullable).
        turns_completed: Number of turns completed.
        total_turns: Total turns in the session (5–10).
        session_data: Turn-by-turn interaction data (nullable).
        summary_data: Session summary (nullable, populated on completion).
        started_at: Session start timestamp.
        completed_at: Session end timestamp (nullable).
    """

    id: int
    user_id: int
    document_id: int
    status: str
    overall_score: float | None = Field(default=None, ge=0.0, le=1.0)
    passed: bool | None = None
    turns_completed: int = Field(ge=0)
    total_turns: int = Field(ge=5, le=10)
    session_data: dict | None = None
    summary_data: dict | None = None
    started_at: datetime
    completed_at: datetime | None = None

    model_config = {"from_attributes": True}


class TurnEvaluationResponse(BaseModel):
    """Response schema for a single turn evaluation in a role-play session.

    Attributes:
        evaluation: Scores dict with factual_accuracy, completeness,
            document_reference_quality (each 0.0–1.0).
        next_question: Next auditor question (null if session complete).
        session_complete: Whether the session has ended.
        current_score: Running weighted average score (0.0–1.0).
    """

    evaluation: dict
    next_question: str | None = None
    session_complete: bool
    current_score: float = Field(ge=0.0, le=1.0)


class DynamicFeedbackResponse(BaseModel):
    """Response schema for paragraph-level dynamic feedback.

    Attributes:
        correct_answer: The correct answer text.
        paragraph_text: Source paragraph containing the answer.
        section_reference: SOP section reference string.
        page_number: Page number in the source document (nullable).
        explanation: LLM-generated explanation of the connection.
    """

    correct_answer: str
    paragraph_text: str
    section_reference: str
    page_number: int | None = None
    explanation: str
