/**
 * Certificate Signing and Storage.
 *
 * Handles the signing of validation certificates via the Signature_Service API
 * and storage in the Document_Service as "Validation Report" documents.
 *
 * This module is called after the certificate PDF is generated. It:
 * 1. Calls the Signature_Service to system-sign the certificate PDF
 * 2. Stores the signed certificate in the Document_Service
 * 3. Returns the Document-UUID of the stored validation report
 */

import type { ValidationCertificate } from "./certificate-generator";

/**
 * Response from the signing and storage API.
 */
export interface SignedCertificateResponse {
  /** Document-UUID assigned to the stored validation report */
  documentUuid: string;
  /** Whether the certificate was successfully signed */
  signed: boolean;
  /** ISO timestamp of the signing event */
  signedAt: string;
}

/**
 * Sign the validation certificate via the Signature_Service and store it
 * in the Document_Service as a "Validation Report".
 *
 * The certificate is system-signed (no user re-authentication required)
 * since it is generated by the automated CSV validation runner.
 *
 * @param certificate - The validation certificate data to sign and store.
 * @param baseUrl - The backend API base URL.
 * @returns The signed certificate response with Document-UUID.
 */
export async function signAndStoreCertificate(
  certificate: ValidationCertificate,
  baseUrl: string
): Promise<SignedCertificateResponse> {
  const response = await fetch(
    `${baseUrl}/api/validation/certificate/sign-and-store`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-CSV-Test-User": "csv_validation_runner",
      },
      body: JSON.stringify({
        certificate,
        document_type: "Validation Report",
        sign: true,
      }),
    }
  );

  if (!response.ok) {
    throw new Error(
      `Failed to sign and store certificate: ${response.status} ${response.statusText}`
    );
  }

  const data = (await response.json()) as {
    document_uuid: string;
    signed: boolean;
    signed_at: string;
  };

  return {
    documentUuid: data.document_uuid,
    signed: data.signed,
    signedAt: data.signed_at,
  };
}
