"""FastAPI router for report upload and extraction endpoints.

Provides the PDF upload endpoint that extracts field values from
completed offline PDFs using the PDFExtractor service.

References:
    - Design doc Section 4: PDF Extraction (PyMuPDF)
    - Requirements 5: PDF Data Extraction and Database Mapping
"""

from fastapi import APIRouter, Depends, HTTPException, UploadFile
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from alcoabase.database import get_db_session
from alcoabase.dependencies.tenant import TenantContext, get_tenant_context
from alcoabase.models.report import Report, ReportFieldValue
from alcoabase.models.template import Template
from alcoabase.schemas.report import (
    ReportResponse,
    UploadErrorResponse,
    ValidationErrorDetail,
)
from alcoabase.services.pdf_extractor import PDFExtractor

router = APIRouter(prefix="/reports", tags=["Reports"])

# Module-level service instance
_pdf_extractor = PDFExtractor()


def get_pdf_extractor() -> PDFExtractor:
    """Provide the PDFExtractor instance as a dependency.

    Returns:
        The module-level PDFExtractor instance.
    """
    return _pdf_extractor


@router.post(
    "/upload-pdf",
    response_model=ReportResponse,
    status_code=201,
    responses={400: {"model": UploadErrorResponse}},
)
async def upload_pdf(
    file: UploadFile,
    user_id: int = 1,
    session: AsyncSession = Depends(get_db_session),
    extractor: PDFExtractor = Depends(get_pdf_extractor),
    tenant: TenantContext = Depends(get_tenant_context),
) -> ReportResponse:
    """Upload a completed PDF and extract field values.

    Reads the embedded Document-UUID to match the PDF to a template,
    extracts all field values by Field-UUID, validates types, and
    persists atomically (all-or-nothing).

    Args:
        file: The uploaded PDF file.
        user_id: ID of the uploading user (simplified auth for now).
        session: Database session dependency.
        extractor: PDFExtractor dependency.

    Returns:
        The created Report with extracted field values.

    Raises:
        HTTPException: 400 for unknown Document-UUID or validation failures.
    """
    # Read the PDF bytes
    pdf_bytes = await file.read()

    if not pdf_bytes:
        raise HTTPException(status_code=400, detail="Empty file uploaded.")

    # Step 1: Read the Document-UUID from the PDF
    document_uuid = extractor.read_document_uuid(pdf_bytes)
    if not document_uuid:
        raise HTTPException(
            status_code=400,
            detail="PDF does not contain a valid __DOC_UUID__ field. "
            "This PDF was not generated by AlcoaBase.",
        )

    # Step 2: Match Document-UUID to a template
    result = await session.execute(
        select(Template)
        .where(Template.document_uuid == document_uuid)
        .options(selectinload(Template.fields))
    )
    template = result.scalar_one_or_none()

    if template is None:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown Document-UUID: '{document_uuid}'. "
            f"No template found matching this PDF.",
        )

    # TODO: Validate cross-tenant template reference — reject with 403 if
    # template belongs to a different company than tenant.company_id

    # Step 3: Extract and validate field values
    extracted = extractor.extract_data(pdf_bytes, template)

    # Step 4: Check for validation errors — reject entirely if any
    if not extracted.is_valid:
        error_details = [
            ValidationErrorDetail(
                field_uuid=err.field_uuid,
                field_label=err.field_label,
                expected_type=err.expected_type,
                actual_value=err.actual_value,
                message=err.message,
            )
            for err in extracted.validation_errors
        ]
        raise HTTPException(
            status_code=400,
            detail={
                "detail": "Type validation failed. No data was persisted.",
                "validation_errors": [e.model_dump() for e in error_details],
            },
        )

    # Step 5: Atomic persistence — create Report + all ReportFieldValues
    # TODO: Set company_id=tenant.company_id on created resource
    report = Report(
        document_uuid=document_uuid,
        template_id=template.id,
        uploaded_by=user_id,
        status="Extracted",
    )
    session.add(report)
    await session.flush()

    # Create field value records
    for template_field in template.fields:
        value = extracted.field_values.get(template_field.field_uuid)
        field_value = ReportFieldValue(
            report_id=report.id,
            field_uuid=template_field.field_uuid,
            value=value,
            validated=True,
        )
        session.add(field_value)

    await session.flush()

    # Reload report with field_values relationship
    result = await session.execute(
        select(Report)
        .where(Report.id == report.id)
        .options(selectinload(Report.field_values))
    )
    report = result.scalar_one()

    return ReportResponse.model_validate(report)
