"""Audit access logger service for meta-auditing of audit trail access.

This module provides the AuditAccessLogger class that records every
access to the audit trail viewer (views and exports). It implements
a fire-and-forget pattern: each access event is committed immediately
to the audit_access_log table.

Additionally, provides the `log_document_access` function for recording
document download and content preview events to the audit trail.

The service is intentionally append-only — no update or delete methods
are provided, enforcing immutability at the service layer per ALCOA+
and 21 CFR Part 11 requirements.

References:
    - Requirement 6.4: Log all download and content access events to the audit trail
    - Requirement 11.1: Log access events with user identity, timestamp, and filters
    - Requirement 11.2: Log export events with user identity, timestamp, filters, and event count
    - Requirement 11.3: Dedicated audit_access_log table with same immutability rules
"""

import logging

from sqlalchemy.ext.asyncio import AsyncSession

from alcoabase.models.audit_access_log import AuditAccessLog
from alcoabase.models.document_access_log import DocumentAccessLog

logger = logging.getLogger(__name__)


class AuditAccessLogger:
    """Service for logging access to the audit trail.

    Records every view and export action performed against the audit
    trail. This enables meta-auditing: knowing who reviewed the audit
    data and when.

    This service is append-only. No update or delete methods exist,
    enforcing immutability at the service layer.
    """

    async def log_access(
        self,
        session: AsyncSession,
        user_id: int,
        company_id: int,
        action: str,
        filters_applied: dict | None = None,
        event_count: int | None = None,
    ) -> None:
        """Record an audit trail access event.

        Creates an AuditAccessLog record with a server-side timestamp
        and commits immediately (fire-and-forget pattern). The timestamp
        is generated by the database server via server_default=func.now().

        Args:
            session: Active async database session.
            user_id: ID of the user who accessed the audit trail.
            company_id: ID of the company context for the access.
            action: Type of access — "view" for list/detail requests,
                "export" for PDF export requests.
            filters_applied: JSON-serializable dict of active filter
                parameters at the time of access. None if no filters
                were applied.
            event_count: Number of events exported. Populated only for
                export actions (None for view actions).
        """
        log_entry = AuditAccessLog(
            user_id=user_id,
            company_id=company_id,
            action=action,
            filters_applied=filters_applied,
            event_count=event_count,
        )

        session.add(log_entry)

        try:
            await session.commit()
        except Exception:
            await session.rollback()
            logger.exception(
                "Failed to log audit access event for user_id=%d, "
                "company_id=%d, action=%s",
                user_id,
                company_id,
                action,
            )


async def log_document_access(
    session: AsyncSession,
    user_id: int,
    document_uuid: str,
    major_version: int,
    minor_version: int,
    action: str,
) -> None:
    """Record a document access event to the audit trail.

    Creates a DocumentAccessLog record with a server-side timestamp
    and commits immediately (fire-and-forget pattern). The timestamp
    is generated by the database server via server_default=func.now().

    This function logs download and content preview events for ALCOA+
    compliance, enabling full traceability of who accessed which
    document content and when.

    Args:
        session: Active async database session.
        user_id: ID of the user who accessed the document.
        document_uuid: UUID of the accessed document (YYYY-NNNNN format).
        major_version: Major version number of the accessed document version.
        minor_version: Minor version number of the accessed document version.
        action: Type of access — "download" or "content_preview".

    Raises:
        ValueError: If action is not "download" or "content_preview".
    """
    valid_actions = {"download", "content_preview"}
    if action not in valid_actions:
        raise ValueError(
            f"Invalid action '{action}'. Must be one of: {valid_actions}"
        )

    log_entry = DocumentAccessLog(
        user_id=user_id,
        document_uuid=document_uuid,
        major_version=major_version,
        minor_version=minor_version,
        action=action,
    )

    session.add(log_entry)

    try:
        await session.commit()
    except Exception:
        await session.rollback()
        logger.exception(
            "Failed to log document access event for user_id=%d, "
            "document_uuid=%s, version=%d.%d, action=%s",
            user_id,
            document_uuid,
            major_version,
            minor_version,
            action,
        )
