"""Audit access logger service for meta-auditing of audit trail access.

This module provides the AuditAccessLogger class that records every
access to the audit trail viewer (views and exports). It implements
a fire-and-forget pattern: each access event is committed immediately
to the audit_access_log table.

The service is intentionally append-only — no update or delete methods
are provided, enforcing immutability at the service layer per ALCOA+
and 21 CFR Part 11 requirements.

References:
    - Requirement 11.1: Log access events with user identity, timestamp, and filters
    - Requirement 11.2: Log export events with user identity, timestamp, filters, and event count
    - Requirement 11.3: Dedicated audit_access_log table with same immutability rules
"""

import logging

from sqlalchemy.ext.asyncio import AsyncSession

from alcoabase.models.audit_access_log import AuditAccessLog

logger = logging.getLogger(__name__)


class AuditAccessLogger:
    """Service for logging access to the audit trail.

    Records every view and export action performed against the audit
    trail. This enables meta-auditing: knowing who reviewed the audit
    data and when.

    This service is append-only. No update or delete methods exist,
    enforcing immutability at the service layer.
    """

    async def log_access(
        self,
        session: AsyncSession,
        user_id: int,
        company_id: int,
        action: str,
        filters_applied: dict | None = None,
        event_count: int | None = None,
    ) -> None:
        """Record an audit trail access event.

        Creates an AuditAccessLog record with a server-side timestamp
        and commits immediately (fire-and-forget pattern). The timestamp
        is generated by the database server via server_default=func.now().

        Args:
            session: Active async database session.
            user_id: ID of the user who accessed the audit trail.
            company_id: ID of the company context for the access.
            action: Type of access — "view" for list/detail requests,
                "export" for PDF export requests.
            filters_applied: JSON-serializable dict of active filter
                parameters at the time of access. None if no filters
                were applied.
            event_count: Number of events exported. Populated only for
                export actions (None for view actions).
        """
        log_entry = AuditAccessLog(
            user_id=user_id,
            company_id=company_id,
            action=action,
            filters_applied=filters_applied,
            event_count=event_count,
        )

        session.add(log_entry)

        try:
            await session.commit()
        except Exception:
            await session.rollback()
            logger.exception(
                "Failed to log audit access event for user_id=%d, "
                "company_id=%d, action=%s",
                user_id,
                company_id,
                action,
            )
