"""PDF Extractor service using PyMuPDF for AcroForm data extraction.

Reads completed offline PDFs and maps field values back to relational
database columns using Field-UUIDs as AcroForm field identifiers.
No OCR or visual label dependency — purely AcroForm field name matching.

References:
    - Design doc Section 4: PDF Extraction (PyMuPDF)
    - Requirements 5: PDF Data Extraction and Database Mapping
    - Requirements 6: PDF Round-Trip Integrity
"""

from dataclasses import dataclass, field

import fitz  # PyMuPDF

from alcoabase.models.template import Template, TemplateField
from alcoabase.services.field_validator import (
    FieldValidationError,
    validate_single_value,
)


# ---------------------------------------------------------------------------
# Data classes for extraction results
# ---------------------------------------------------------------------------


# Backward-compatible alias: ValidationError is now FieldValidationError
# from the shared field_validator module.
ValidationError = FieldValidationError


@dataclass
class ExtractedReport:
    """Result of PDF data extraction.

    Attributes:
        document_uuid: The Document-UUID read from the hidden field.
        field_values: Mapping of Field-UUID to extracted string value.
        validation_errors: List of validation errors (empty if all valid).
        is_valid: Whether all field values passed type validation.
    """

    document_uuid: str
    field_values: dict[str, str | None] = field(default_factory=dict)
    validation_errors: list[ValidationError] = field(default_factory=list)
    is_valid: bool = True


# ---------------------------------------------------------------------------
# PDF Extractor Service
# ---------------------------------------------------------------------------


class PDFExtractor:
    """Service for extracting field values from completed AcroForm PDFs.

    Reads the hidden __DOC_UUID__ field to identify the source template,
    then extracts each field value by its Field-UUID AcroForm name.
    Validates extracted values against the template field types.

    The extractor forms a parser pair with PDFGenerator — the round-trip
    property is: extract(generate(template, data)) == data.
    """

    def extract_data(self, pdf_bytes: bytes, template: Template) -> ExtractedReport:
        """Extract field values from a completed offline PDF.

        Opens the PDF with PyMuPDF, reads the __DOC_UUID__ hidden field
        to get the Document-UUID, then reads each AcroForm field by its
        Field-UUID name and validates against the template field types.

        Args:
            pdf_bytes: The raw PDF file bytes.
            template: The matched Template instance with fields loaded.

        Returns:
            ExtractedReport with document_uuid, field_values, and
            any validation errors.

        Raises:
            ValueError: If the PDF cannot be opened or has no AcroForm fields.
        """
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        try:
            # Read all AcroForm field values from the PDF
            pdf_fields = self._read_acroform_fields(doc)

            # Read the Document-UUID from the hidden field
            document_uuid = pdf_fields.get("__DOC_UUID__")
            if not document_uuid:
                raise ValueError(
                    "PDF does not contain a __DOC_UUID__ hidden field. "
                    "This PDF was not generated by AlcoaBase."
                )

            # Extract field values by Field-UUID
            field_values: dict[str, str | None] = {}
            for template_field in template.fields:
                raw_value = pdf_fields.get(template_field.field_uuid)
                field_values[template_field.field_uuid] = raw_value

            # Validate field values against template types
            validation_errors = self._validate_field_values(
                field_values, template.fields
            )

            return ExtractedReport(
                document_uuid=document_uuid,
                field_values=field_values,
                validation_errors=validation_errors,
                is_valid=len(validation_errors) == 0,
            )
        finally:
            doc.close()

    def read_document_uuid(self, pdf_bytes: bytes) -> str | None:
        """Read only the Document-UUID from a PDF without full extraction.

        Useful for template matching before full extraction.

        Args:
            pdf_bytes: The raw PDF file bytes.

        Returns:
            The Document-UUID string, or None if not found.
        """
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        try:
            pdf_fields = self._read_acroform_fields(doc)
            return pdf_fields.get("__DOC_UUID__")
        finally:
            doc.close()

    def _read_acroform_fields(self, doc: fitz.Document) -> dict[str, str | None]:
        """Read all AcroForm field names and values from the PDF.

        Iterates over all pages and widgets to collect field data.

        Args:
            doc: An open PyMuPDF Document instance.

        Returns:
            Dictionary mapping field names to their string values.
        """
        fields: dict[str, str | None] = {}
        for page in doc:
            for widget in page.widgets():
                if widget.field_name:
                    value = widget.field_value
                    # Normalize empty strings to None for consistency
                    if value == "" or value is None:
                        fields[widget.field_name] = None
                    else:
                        fields[widget.field_name] = value
        return fields

    def _validate_field_values(
        self,
        field_values: dict[str, str | None],
        template_fields: list[TemplateField],
    ) -> list[ValidationError]:
        """Validate extracted values against template field types.

        Checks each non-None value against its expected type:
        - Float: must be a valid float number
        - Integer: must be a valid integer
        - Text: any string (always valid)
        - Date: must be YYYY-MM-DD format
        - Boolean: must be "Yes", "Off", or similar checkbox values

        Args:
            field_values: Mapping of Field-UUID to extracted value.
            template_fields: List of TemplateField definitions.

        Returns:
            List of ValidationError instances for failed validations.
        """
        errors: list[ValidationError] = []

        for template_field in template_fields:
            value = field_values.get(template_field.field_uuid)

            # None/empty values are allowed (field not filled)
            if value is None:
                continue

            error = self._validate_single_value(
                value=value,
                field_type=template_field.field_type,
                field_uuid=template_field.field_uuid,
                field_label=template_field.field_label,
            )
            if error:
                errors.append(error)

        return errors

    def _validate_single_value(
        self,
        value: str,
        field_type: str,
        field_uuid: str,
        field_label: str,
    ) -> ValidationError | None:
        """Validate a single field value against its expected type.

        Delegates to the shared validate_single_value utility with
        PDF context for backward-compatible boolean validation.

        Args:
            value: The extracted string value.
            field_type: Expected type (Text, Float, Integer, Date, Boolean).
            field_uuid: The Field-UUID for error reporting.
            field_label: Human-readable label for error reporting.

        Returns:
            A ValidationError if validation fails, None if valid.
        """
        return validate_single_value(
            value=value,
            field_type=field_type,
            field_uuid=field_uuid,
            field_label=field_label,
            context="pdf",
        )
