"""initial_schema

Revision ID: 3602b506bc61
Revises: 
Create Date: 2026-05-01 18:04:35.313698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3602b506bc61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_csv_test_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agent_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agent_definitions_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_definitions'))
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_uuid', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('folder_path', sa.String(length=1000), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('is_csv_validation_record', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_documents_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_document_uuid'), 'documents', ['document_uuid'], unique=True)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_uuid', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('json_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_templates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index(op.f('ix_templates_document_uuid'), 'templates', ['document_uuid'], unique=True)
    op.create_table('training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sop_document_uuid', sa.String(length=12), nullable=False),
    sa.Column('sop_version', sa.String(length=20), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_training_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_records'))
    )
    op.create_index(op.f('ix_training_records_sop_document_uuid'), 'training_records', ['sop_document_uuid'], unique=False)
    op.create_table('training_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sop_document_uuid', sa.String(length=12), nullable=False),
    sa.Column('sop_version', sa.String(length=20), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=False),
    sa.Column('task_title', sa.Text(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_training_tasks_assigned_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_tasks'))
    )
    op.create_index(op.f('ix_training_tasks_sop_document_uuid'), 'training_tasks', ['sop_document_uuid'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('virtual_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tag_filter', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.String(length=50), nullable=False),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_virtual_folders_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_virtual_folders')),
    sa.UniqueConstraint('name', name=op.f('uq_virtual_folders_name'))
    )
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('document_tag', sa.String(length=100), nullable=False),
    sa.Column('bpmn_xml', sa.Text(), nullable=False),
    sa.Column('signature_required_transitions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('training_trigger_transitions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workflow_definitions_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_definitions'))
    )
    op.create_index(op.f('ix_workflow_definitions_document_tag'), 'workflow_definitions', ['document_tag'], unique=True)
    op.create_table('document_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_states_document_id_documents')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_document_states_updated_by_users')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], name=op.f('fk_document_states_workflow_id_workflow_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_states'))
    )
    op.create_table('document_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_tags_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_tags'))
    )
    op.create_index(op.f('ix_document_tags_tag'), 'document_tags', ['tag'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('major_version', sa.Integer(), nullable=False),
    sa.Column('minor_version', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_document_versions_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions'))
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_uuid', sa.String(length=12), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_reports_template_id_templates')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_reports_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_document_uuid'), 'reports', ['document_uuid'], unique=False)
    op.create_table('template_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('field_uuid', sa.String(length=40), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('field_label', sa.String(length=200), nullable=False),
    sa.Column('field_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_template_fields_template_id_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_fields'))
    )
    op.create_index(op.f('ix_template_fields_field_uuid'), 'template_fields', ['field_uuid'], unique=True)
    op.create_table('report_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('field_uuid', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_field_values_report_id_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_field_values'))
    )
    op.create_index(op.f('ix_report_field_values_field_uuid'), 'report_field_values', ['field_uuid'], unique=False)
    op.create_table('signature_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_uuid', sa.String(length=12), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('signer_user_id', sa.Integer(), nullable=False),
    sa.Column('transition', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signature_hash', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_signature_records_document_version_id_document_versions')),
    sa.ForeignKeyConstraint(['signer_user_id'], ['users.id'], name=op.f('fk_signature_records_signer_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signature_records'))
    )
    op.create_index(op.f('ix_signature_records_document_uuid'), 'signature_records', ['document_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signature_records_document_uuid'), table_name='signature_records')
    op.drop_table('signature_records')
    op.drop_index(op.f('ix_report_field_values_field_uuid'), table_name='report_field_values')
    op.drop_table('report_field_values')
    op.drop_index(op.f('ix_template_fields_field_uuid'), table_name='template_fields')
    op.drop_table('template_fields')
    op.drop_index(op.f('ix_reports_document_uuid'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_tags_tag'), table_name='document_tags')
    op.drop_table('document_tags')
    op.drop_table('document_states')
    op.drop_index(op.f('ix_workflow_definitions_document_tag'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_table('virtual_folders')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_training_tasks_sop_document_uuid'), table_name='training_tasks')
    op.drop_table('training_tasks')
    op.drop_index(op.f('ix_training_records_sop_document_uuid'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_templates_document_uuid'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_documents_document_uuid'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('agent_definitions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
